### ISSUE TITLE
Permanent disable?

### ISSUE THREAD

**Issue by lonix1** [nunofarruca/WindowIsReady_Remover#4]
This extension is really helpful, thanks!

But do you know whether there is a permanent way to disable the "is ready" notification? For example using `dconf` or editing some file, etc.?

**Comment by nunofarruca** [comment]
Oh I'm not experienced on how the dconf works.
The file I change behavior is: _windowAttentionHandler.js_ and 3 years ago they allowed extensions to disconnect the signal. Since then, the changes on the file don't lead me on a way that is possible by dconf to do the same.
So I think you still need to use an extension that does disconnect the signal when is loaded.
